-- =============================================
-- SECTION 1: DDL (DATA DEFINITION)
-- =============================================

-- CLEAN DROP (SAFE RE-RUN)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE VOLUNTEER_CERTIFICATION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TEACHING_ASSIGNMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TASK_ASSIGNMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOGISTICS_TASK CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE STUDENT_RECORD CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE REGISTRATION_APPLICATION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RECEIPT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DONATION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EXPENSE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE REPORT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROGRAM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE BUDGET CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE STUDENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PARENT_GUARDIAN CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE VOLUNTEER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AVAILABLE_SUBJECT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EMPLOYMENT_CONTRACT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DONOR CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- MODULE 1: EMPLOYMENT & HR
CREATE TABLE EMPLOYMENT_CONTRACT (
    CONTRACT_ID VARCHAR2(20) PRIMARY KEY,
    CONTRACT_START DATE,
    CONTRACT_END DATE,
    CONTRACT_SALARY NUMBER(10,2),
    CONTRACT_TERMS VARCHAR2(500),
    CONTRACT_STATUS VARCHAR2(20)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID VARCHAR2(20) PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR2(100),
    EMPLOYEE_NRIC VARCHAR2(20),
    EMPLOYEE_POSITION VARCHAR2(50),
    EMPLOYEE_EMAIL VARCHAR2(100),
    EMPLOYEE_CONTACT VARCHAR2(20),
    EMPLOYEE_BANK_ACCOUNT VARCHAR2(50),
    EMPLOYEE_BANK_NAME VARCHAR2(50),
    CONTRACT_ID VARCHAR2(20),
    CONSTRAINT FK_EMP_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES EMPLOYMENT_CONTRACT(CONTRACT_ID)
);

-- MODULE 2: PARENT & STUDENT
CREATE TABLE PARENT_GUARDIAN (
    PARENT_ID VARCHAR2(20) PRIMARY KEY,
    NRIC VARCHAR2(20) UNIQUE,
    CONTACT_NUMBER VARCHAR2(20),
    HOME_ADDRESS VARCHAR2(255),
    OCCUPATION VARCHAR2(100),
    HOUSEHOLD_INCOME NUMBER(10,2),
    MARITAL_STATUS VARCHAR2(20)
);

CREATE TABLE STUDENT (
    STUDENT_ID VARCHAR2(20) PRIMARY KEY,
    STUDENT_FULL_NAME VARCHAR2(100),
    STUDENT_NRIC VARCHAR2(20) UNIQUE,
    STUDENT_DATE_OF_BIRTH DATE,
    STUDENT_GENDER VARCHAR2(10),
    STUDENT_CURRENT_SCHOOL VARCHAR2(100),
    STUDENT_STANDARD_FORM VARCHAR2(20),
    STUDENT_HEALTH_CONDITIONS VARCHAR2(255),
    PARENT_ID VARCHAR2(20),
    CONSTRAINT FK_STUDENT_PARENT FOREIGN KEY (PARENT_ID) REFERENCES PARENT_GUARDIAN(PARENT_ID)
);

-- MODULE 3: VOLUNTEER & SUBJECT
CREATE TABLE VOLUNTEER (
    VOLUNTEER_ID VARCHAR2(20) PRIMARY KEY,
    VOLUNTEER_NRIC VARCHAR2(20),
    VOLUNTEER_CONTACT_NUMBER VARCHAR2(20),
    VOLUNTEER_EMAIL_ADDRESS VARCHAR2(100),
    VOLUNTEER_INSTITUTION_NAME VARCHAR2(100),
    VOLUNTEER_COURSE_MAJOR VARCHAR2(100),
    VOLUNTEER_YEAR_OF_STUDY NUMBER(1),
    VOLUNTEER_OWN_TRANSPORT CHAR(1),
    VOLUNTEER_REGISTRATION_DATE DATE,
    VOLUNTEER_STATUS VARCHAR2(20)
);

CREATE TABLE AVAILABLE_SUBJECT (
    SUBJECT_ID VARCHAR2(20) PRIMARY KEY,
    SUBJECT_NAME VARCHAR2(50),
    SUBJECT_LEVEL VARCHAR2(20),
    SYLLABUS_CODE VARCHAR2(20)
);

-- MODULE 4: BUDGET & PROGRAM
CREATE TABLE BUDGET (
    BUDGET_ID VARCHAR2(20) PRIMARY KEY,
    FISCAL_YEAR NUMBER(4),
    TOTAL_ALLOCATION NUMBER(10,2),
    BUDGET_DESCRIPTION VARCHAR2(255)
);

CREATE TABLE PROGRAM (
    PROGRAM_ID VARCHAR2(20) PRIMARY KEY,
    PROGRAM_NAME VARCHAR2(100),
    PROGRAM_TYPE VARCHAR2(50),
    PROGRAM_DESCRIPTION VARCHAR2(255),
    PROGRAM_START_DATE DATE,
    PROGRAM_END_DATE DATE,
    PROGRAM_VENUE VARCHAR2(100),
    BUDGET_ID VARCHAR2(20),
    EMPLOYEE_ID VARCHAR2(20),
    CONSTRAINT FK_PROGRAM_BUDGET FOREIGN KEY (BUDGET_ID) REFERENCES BUDGET(BUDGET_ID),
    CONSTRAINT FK_PROGRAM_EMP FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

-- MODULE 5: LOGISTICS & TEACHING
CREATE TABLE LOGISTICS_TASK (
    TASK_ID VARCHAR2(20) PRIMARY KEY,
    TASK_NAME VARCHAR2(100),
    TASK_DESCRIPTION VARCHAR2(255),
    TASK_DEADLINE DATE,
    TASK_STATUS VARCHAR2(20),
    EMPLOYEE_ID VARCHAR2(20),
    PROGRAM_ID VARCHAR2(20),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAM(PROGRAM_ID)
);

CREATE TABLE TASK_ASSIGNMENT (
    TASK_ID VARCHAR2(20),
    EMPLOYEE_ID VARCHAR2(20),
    ROLE_IN_TASK VARCHAR2(50),
    PRIMARY KEY (TASK_ID, EMPLOYEE_ID),
    FOREIGN KEY (TASK_ID) REFERENCES LOGISTICS_TASK(TASK_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE TEACHING_ASSIGNMENT (
    ASSIGNMENT_ID VARCHAR2(20) PRIMARY KEY,
    STUDENT_ID VARCHAR2(20),
    VOLUNTEER_ID VARCHAR2(20),
    SUBJECT_ID VARCHAR2(20),
    DAY_OF_WEEK VARCHAR2(15),
    TIME_SLOT VARCHAR2(30),
    TERM_SEMESTER VARCHAR2(20),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (VOLUNTEER_ID) REFERENCES VOLUNTEER(VOLUNTEER_ID),
    FOREIGN KEY (SUBJECT_ID) REFERENCES AVAILABLE_SUBJECT(SUBJECT_ID)
);

CREATE TABLE VOLUNTEER_CERTIFICATION (
    VOLUNTEER_ID VARCHAR2(20),
    STUDENT_ID VARCHAR2(20),
    CERTIFICATION_DATE DATE,
    PRIMARY KEY (VOLUNTEER_ID, STUDENT_ID),
    FOREIGN KEY (VOLUNTEER_ID) REFERENCES VOLUNTEER(VOLUNTEER_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);

-- MODULE 6: STUDENT PROCESS
CREATE TABLE REGISTRATION_APPLICATION (
    APP_ID VARCHAR2(20) PRIMARY KEY,
    APP_SUBMISSION_DATE DATE,
    APP_STATUS VARCHAR2(20),
    APP_REMARKS VARCHAR2(255),
    STUDENT_ID VARCHAR2(20),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);

CREATE TABLE STUDENT_RECORD (
    RECORD_ID VARCHAR2(20) PRIMARY KEY,
    ENROLLMENT_DATE DATE,
    RECORD_STATUS VARCHAR2(20),
    RECORD_NOTES VARCHAR2(255),
    STUDENT_ID VARCHAR2(20),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);

-- MODULE 7: FINANCE & REPORTING
CREATE TABLE DONOR (
    DONOR_ID VARCHAR2(20) PRIMARY KEY,
    DONOR_NAME VARCHAR2(100),
    DONOR_TYPE VARCHAR2(30),
    DONOR_CONTACT VARCHAR2(20),
    DONOR_EMAIL VARCHAR2(100),
    DONOR_ADDRESS VARCHAR2(255),
    DONOR_TAX_ID VARCHAR2(30)
);

CREATE TABLE DONATION (
    DONATION_ID VARCHAR2(20) PRIMARY KEY,
    AMOUNT NUMBER(10,2),
    DATE_RECEIVED DATE,
    PAYMENT_METHOD VARCHAR2(30),
    DESIGNATION_TYPE VARCHAR2(50),
    PROGRAM_ID VARCHAR2(20),
    DONOR_ID VARCHAR2(20),
    FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAM(PROGRAM_ID),
    FOREIGN KEY (DONOR_ID) REFERENCES DONOR(DONOR_ID)
);

CREATE TABLE EXPENSE (
    EXPENSE_ID VARCHAR2(20) PRIMARY KEY,
    EXPENSE_AMOUNT NUMBER(10,2),
    EXPENSE_DATE DATE,
    EXPENSE_DESCRIPTION VARCHAR2(255),
    EXPENSE_CATEGORY VARCHAR2(50),
    BUDGET_ID VARCHAR2(20),
    PROGRAM_ID VARCHAR2(20),
    FOREIGN KEY (BUDGET_ID) REFERENCES BUDGET(BUDGET_ID),
    FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAM(PROGRAM_ID)
);

CREATE TABLE RECEIPT (
    RECEIPT_NUMBER VARCHAR2(20) PRIMARY KEY,
    ISSUE_DATE DATE,
    TAX_EXEMPT_STATUS VARCHAR2(20),
    DONATION_ID VARCHAR2(20),
    FOREIGN KEY (DONATION_ID) REFERENCES DONATION(DONATION_ID)
);

CREATE TABLE REPORT (
    REPORT_ID VARCHAR2(20) PRIMARY KEY,
    SUBMISSION_DATE DATE,
    EXECUTIVE_SUMMARY VARCHAR2(500),
    ISSUES_ENCOUNTERED VARCHAR2(255),
    PROGRAM_ID VARCHAR2(20),
    FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAM(PROGRAM_ID)
);


-- ============================================================
-- SECTION 2: DDL (ALTER TABLE)
-- ============================================================

-- to store Parent Names for searching
ALTER TABLE PARENT_GUARDIAN ADD PARENT_NAME VARCHAR2(100);

-- to track Program Status explicitly
ALTER TABLE PROGRAM ADD PROGRAM_STATUS VARCHAR2(20);


-- Update the existing records
UPDATE PARENT_GUARDIAN SET PARENT_NAME = 'Ali bin Abu' WHERE PARENT_ID = 'PG002';
UPDATE PARENT_GUARDIAN SET PARENT_NAME = 'Wong Mei Ling' WHERE PARENT_ID = 'PG003';
UPDATE PARENT_GUARDIAN SET PARENT_NAME = 'Rajesh Kumar' WHERE PARENT_ID = 'PG004';
UPDATE PARENT_GUARDIAN SET PARENT_NAME = 'Siti Aminah' WHERE PARENT_ID = 'PG005';
UPDATE PARENT_GUARDIAN SET PARENT_NAME = 'Lim Wei Hong' WHERE PARENT_ID = 'PG006';
UPDATE PARENT_GUARDIAN SET PARENT_NAME = 'John Doe' WHERE PARENT_ID = 'PG007';
UPDATE PARENT_GUARDIAN SET PARENT_NAME = 'Chong Wei' WHERE PARENT_ID = 'PG008';
UPDATE PARENT_GUARDIAN SET PARENT_NAME = 'Dr. Sarah Lee' WHERE PARENT_ID = 'PG009';
UPDATE PARENT_GUARDIAN SET PARENT_NAME = 'Pak Mat' WHERE PARENT_ID = 'PG010';
UPDATE PARENT_GUARDIAN SET PARENT_NAME = 'Muthu Sami' WHERE PARENT_ID = 'PG011';

UPDATE PROGRAM SET PROGRAM_STATUS = 'ONGOING' WHERE PROGRAM_ID = 'P001';
